/*
 * DialogCreatePerson.java
 * Provides GUI to create a person other than a swimmer. 
 * 
 */
package swimmingcompetition.ux;

import swimmingcompetition.simulator.Person;
import swimmingcompetition.ux.viewmodels.ModelCreatePerson;
import swimmingcompetition.ux.viewmodels.UIUpdater;

/**
 *
 * @author Wickramaranga
 */
public class DialogCreatePerson extends javax.swing.JDialog {

    private final ModelCreatePerson personModel;
    private boolean okay;

    /**
     * Creates new form DialogCreatePerson
     *
     * @param parent parent of this frame.
     * @param modal whether this form is a modal.
     */
    public DialogCreatePerson(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        personModel = new ModelCreatePerson();
        personModel.setName("");
        personModel.setRole("Spectator");
        okay = false;
        initComponents();

        personModel.setUpdater(new UIUpdater() {

            @Override
            public void updateUI(String partToUpdate) {
                switch (partToUpdate) {
                    case "Message":
                        jLabelMsg.setText(personModel.getMessage());
                        break;
                    default:
                        assert false;
                        break;
                }
            }
        });
        jButtonOk.setEnabled(personModel.isValid());
    }

    public Person getPerson() {
        return personModel.getObject();
    }

    public boolean isOkay() {
        return okay;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRole = new javax.swing.JLabel();
        jComboRole = new javax.swing.JComboBox();
        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jLabelMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new person");
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabelRole.setText("Role");

        jComboRole.setBackground(new java.awt.Color(0, 204, 204));
        jComboRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Judge", "Spectator", "Supporting Staff Member" }));
        jComboRole.setSelectedIndex(1);
        jComboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboRoleActionPerformed(evt);
            }
        });

        jLabelName.setText("Name");

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });
        jTextName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNameKeyReleased(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(0, 204, 204));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOk.setBackground(new java.awt.Color(0, 204, 204));
        jButtonOk.setText("Okay");
        jButtonOk.setToolTipText("");
        jButtonOk.setEnabled(false);
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelMsg.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMsg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMsg.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRole)
                            .addComponent(jLabelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboRole, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addGap(18, 18, 18)
                .addComponent(jLabelMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOk))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNameKeyReleased
        personModel.setName(jTextName.getText());
        jButtonOk.setEnabled(personModel.isValid());
    }//GEN-LAST:event_jTextNameKeyReleased

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        okay = true;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboRoleActionPerformed
        personModel.setRole(jComboRole.getSelectedItem().toString());
        jButtonOk.setEnabled(personModel.isValid());
    }//GEN-LAST:event_jComboRoleActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        if (personModel.isValid()) {
            okay = true;
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jTextNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboRole;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables
}
