/*
 * DialogCreateSwimmer.java
 * Provides GUI to create a new swimmer object.
 * 
 */
package swimmingcompetition.ux;

import swimmingcompetition.simulator.Swimmer;
import swimmingcompetition.ux.viewmodels.ModelCreateSwimmer;
import swimmingcompetition.ux.viewmodels.UIUpdater;

/**
 *
 * @author Wickramaranga
 */
public class DialogCreateSwimmer extends javax.swing.JDialog {

    private final ModelCreateSwimmer swimmerModel;
    private boolean okay;

    /**
     * Creates new form DialogCreateSwimmer
     *
     * @param parent parent of this frame.
     * @param modal whether this frame is a modal.
     */
    public DialogCreateSwimmer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        swimmerModel = new ModelCreateSwimmer();
        swimmerModel.setName("");
        swimmerModel.setGender("Male");
        okay = false;
        initComponents();

        swimmerModel.setUpdater(new UIUpdater() {

            @Override
            public void updateUI(String partToUpdate) {
                switch (partToUpdate) {
                    case "Message":
                        jLabelMsg.setText(swimmerModel.getMessage());
                        break;
                    default:
                        assert false;
                        break;
                }
            }
        });
        jButtonOk.setEnabled(swimmerModel.isValid());
    }

    /**
     *
     * @return
     */
    public Swimmer getSwimmer() {
        return swimmerModel.getObject();
    }

    /**
     *
     * @return
     */
    public boolean isOkay() {
        return okay;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jComboGender = new javax.swing.JComboBox();
        jLabelGender = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jLabelMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new swimmer");
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabelName.setText("Name");

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });
        jTextName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNameKeyReleased(evt);
            }
        });

        jComboGender.setBackground(new java.awt.Color(0, 204, 204));
        jComboGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jComboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGenderActionPerformed(evt);
            }
        });

        jLabelGender.setText("Gender");

        jButtonCancel.setBackground(new java.awt.Color(0, 204, 204));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOk.setBackground(new java.awt.Color(0, 204, 204));
        jButtonOk.setText("Okay");
        jButtonOk.setEnabled(false);
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelMsg.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMsg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMsg.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGender)
                            .addComponent(jLabelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextName)
                            .addComponent(jComboGender, 0, 147, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 102, Short.MAX_VALUE)
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addComponent(jLabelMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOk))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNameKeyReleased
        swimmerModel.setName(jTextName.getText());
        jButtonOk.setEnabled(swimmerModel.isValid());
    }//GEN-LAST:event_jTextNameKeyReleased

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        okay = true;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGenderActionPerformed
        swimmerModel.setGender(jComboGender.getSelectedItem().toString());
        jButtonOk.setEnabled(swimmerModel.isValid());
    }//GEN-LAST:event_jComboGenderActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        if (swimmerModel.isValid()) {
            okay = true;
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jTextNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboGender;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables
}
