/*
 * Loader.java
 * Bootloader for the software.
 * 
 */
package swimmingcompetition.ux;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import swimmingcompetition.persistence.Persistence;
import swimmingcompetition.simulator.SwimmingCompetition;
import swimmingcompetition.ux.viewmodels.ModelCompetition;

/**
 *
 * @author Wickramaranga
 */
public class Loader extends javax.swing.JFrame {

    /**
     * Creates new form Loader
     */
    public Loader() {
        initComponents();
        reloadFileList();
    }

    private void reloadFileList() {
        this.jListFiles.setModel(new DefaultListModel<String>());
        for (String file : Persistence.listFiles()) {
            ((DefaultListModel<String>) this.jListFiles.getModel()).addElement(file);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListFiles = new javax.swing.JList();
        jLabelWelcome = new javax.swing.JLabel();
        jButtonLoad = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Swimming Competition Simulator");
        setResizable(false);

        jScrollPane1.setViewportView(jListFiles);

        jLabelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setText("<html><body bgcolor=\"#0bccf\">\n<font  size=\"6\" color=\"white\">Welcome</font> to <br /><font size=\"5\" color=\"white\"> Swimming Competition Simulator v1.0!</font> <br />\nSelect a saved competition and load it or, create a new competition to get started. \n</body></html>");

        jButtonLoad.setBackground(new java.awt.Color(0, 204, 204));
        jButtonLoad.setText("Load");
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(0, 204, 204));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCreate.setBackground(new java.awt.Color(0, 102, 255));
        jButtonCreate.setText("Create new competition");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jButtonCreate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoad)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCreate))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        if (jListFiles.getSelectedValuesList().size() < 1) {
            return;
        }

        SwimmingCompetition competition
                = (SwimmingCompetition) Persistence.loadFile(
                        jListFiles.getSelectedValue().toString());

        FrameCompetition frameCompetition
                = new FrameCompetition(new ModelCompetition(competition));
        frameCompetition.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                reloadFileList();
                setVisible(true); // Show Loader again.
            }
        });
        frameCompetition.setVisible(true);
        setVisible(false); // Loader hidden. 
    }//GEN-LAST:event_jButtonLoadActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (jListFiles.getSelectedValuesList().size() < 1) {
            return;
        }
        if (JOptionPane.showConfirmDialog(this,
                                          "Are you sure?",
                                          "Delete?",
                                          JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            Persistence.removeFile(jListFiles.getSelectedValue().toString());
            reloadFileList();
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        final DialogCreateCompetition competitionCreator
                = new DialogCreateCompetition(this, true);

        competitionCreator.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if (competitionCreator.isOkay()) {
                    SwimmingCompetition competition = competitionCreator.getCompetition();
                    FrameCompetition frameCompetition = new FrameCompetition(new ModelCompetition(competition));
                    frameCompetition.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosed(WindowEvent e) {
                            reloadFileList();
                            setVisible(true); // Show Loader again.
                        }
                    });
                    frameCompetition.setVisible(true);
                    setVisible(false); // Loader hidden. 
                }
            }
        });
        competitionCreator.setVisible(true);

    }//GEN-LAST:event_jButtonCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Loader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JList jListFiles;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
